name: helper
description: Crop Disease Detection App
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  tflite: ^1.1.2
  image_picker: ^1.1.2  # Updated to latest stable
  permission_handler: ^11.1.0  # Android 14 compatible
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Latest lint rules
  lints: ^5.1.1  # Updated linter

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt